import type { Dispatch } from 'react';
import type { StudioAction } from '../../app/studioState';
import type { Segment, Speaker } from '../timeline/types';

type ScriptInspectorProps = { segment?: Segment; speakers: Speaker[]; lipSyncEnabled: boolean; dispatch: Dispatch<StudioAction> };
export function ScriptInspector({ segment, speakers, lipSyncEnabled, dispatch }: ScriptInspectorProps) {
  if (!segment) return <aside className="script-inspector">Chưa có phân đoạn.</aside>;
  return <aside className="script-inspector"><div className="inspector-title"><div><span className="eyebrow">EDITOR</span><h2>AI Dubbing Studio</h2></div><span className="status-dot">●</span></div><div className="inspector-tabs"><button className="is-active" type="button">Kịch bản</button><button type="button">Nhân vật</button></div><div className="language-card language-card--source"><div className="language-card__head"><span>🇨🇳 中文 (原声)</span><time>00:15:23</time></div><textarea value={segment.sourceText} onChange={(event: any) => dispatch({ type: 'editSource', segmentId: segment.id, text: event.target.value })} /><div className="romanization">Nǐ zhōngyú láile, wǒ děng nǐ hěnjiǔle.</div></div><div className="swap-marker">↻</div><div className="language-card language-card--target"><div className="language-card__head"><span>🇻🇳 Tiếng Việt (Dubbing)</span><time>00:15:23</time></div><textarea value={segment.translatedText} onChange={(event: any) => dispatch({ type: 'editTranslation', segmentId: segment.id, text: event.target.value })} /></div><div className="voice-section"><label htmlFor="speaker-assignment">Gán giọng cho nhân vật</label><select id="speaker-assignment" value={segment.speakerId} onChange={(event: any) => dispatch({ type: 'assignSpeaker', segmentId: segment.id, speakerId: event.target.value })}>{speakers.map((speaker) => <option key={speaker.id} value={speaker.id}>{speaker.name} · {speaker.label}</option>)}</select><button className="secondary-button" type="button" disabled>▷ Nghe thử giọng · Phase 2</button><button className="ghost-button" type="button" disabled>Regenerate voice · Phase 2</button></div><div className="toggle-row"><div><strong>Đồng bộ khẩu hình</strong><span>V1 dùng duration fitting; visual lip-sync là subsystem tùy chọn.</span></div><button className={`toggle ${lipSyncEnabled ? 'is-on' : ''}`} aria-pressed={lipSyncEnabled} type="button" onClick={() => dispatch({ type: 'toggleLipSync' })}><i /></button></div></aside>;
}
